var annotated_dup =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "Diamond_Board", "class_diamond___board.html", "class_diamond___board" ],
    [ "Diamond_UI", "class_diamond___u_i.html", "class_diamond___u_i" ],
    [ "Four_in_a_row_Board", "class_four__in__a__row___board.html", "class_four__in__a__row___board" ],
    [ "Four_in_a_row_UI", "class_four__in__a__row___u_i.html", "class_four__in__a__row___u_i" ],
    [ "FourByFour_Board", "class_four_by_four___board.html", "class_four_by_four___board" ],
    [ "FourByFour_UI", "class_four_by_four___u_i.html", "class_four_by_four___u_i" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "Infinity_Board", "class_infinity___board.html", "class_infinity___board" ],
    [ "Infinity_UI", "class_infinity___u_i.html", "class_infinity___u_i" ],
    [ "Misere_Board", "class_misere___board.html", "class_misere___board" ],
    [ "Misere_UI", "class_misere___u_i.html", "class_misere___u_i" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "Numerical_Board", "class_numerical___board.html", "class_numerical___board" ],
    [ "Numerical_UI", "class_numerical___u_i.html", "class_numerical___u_i" ],
    [ "Obstacles_Board", "class_obstacles___board.html", "class_obstacles___board" ],
    [ "Obstacles_UI", "class_obstacles___u_i.html", "class_obstacles___u_i" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Pyramid_Board", "class_pyramid___board.html", "class_pyramid___board" ],
    [ "Pyramid_UI", "class_pyramid___u_i.html", "class_pyramid___u_i" ],
    [ "SUS_Board", "class_s_u_s___board.html", "class_s_u_s___board" ],
    [ "SUS_UI", "class_s_u_s___u_i.html", "class_s_u_s___u_i" ],
    [ "UI", "class_u_i.html", "class_u_i" ],
    [ "Word_Board", "class_word___board.html", "class_word___board" ],
    [ "Word_UI", "class_word___u_i.html", "class_word___u_i" ],
    [ "XO_5x5_Board", "class_x_o__5x5___board.html", "class_x_o__5x5___board" ],
    [ "XO_5x5_UI", "class_x_o__5x5___u_i.html", "class_x_o__5x5___u_i" ]
];